title: Muktakantha
email: muktakantha@proton.me
name: Muktakantha Azad Ramnath Das
description: >- # this means to ignore newlines until "baseurl:"
  Words from Muktakantha Azad Ramnath Das
baseurl: ''
url: 'https://muktakantha.github.io'
language: en
comments: false
mathjax: true
diagram: true
paginate: 25
paginate_path: '/page:num/'
permalink: /:year/:month/:day/:title
sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
